README.md: Documentaion added
ApeWorX/eth-abi pull request #24
Opened 2018-01-23 16:48 UTC by palash25

Documentation containing examples to the
methods: `eth_abi.decode_single`,
`eth_abi.decode_abi`,` eth_abi.encode_single`
& `eth_abi.encode_abi` added to the README

Closes: https://github.com/ethereum/eth-abi/issues/14

### What was wrong?
Documentation for the aforementioned methods was missing

### How was it fixed?
Documentation was added

#### Cute Animal Picture

![Cute animal picture](https://i.imgur.com/8CVJCxm.jpg)

2018-01-23 16:54 UTC, pipermerriam requested changes
Can you remove all mentions of support for interpolation of hexadecimal encoded data, as well as changing all of the string types to be byte strings with the `b` prefix.

2018-01-23 16:54 UTC, pipermerriam commented on .eggs/README.txt
> +However, it is safe to delete this directory.
This file shouldn't have been committed.

2018-01-23 16:54 UTC, pipermerriam commented on README.md
> +their hexidecimal representation with or without the ``0x`` prefix.
This should be changed to state that `data` **must** be of type bytes.  Both text and hex encoded data type detection has been deprecated.

2018-01-23 16:54 UTC, pipermerriam commented on README.md
> +    >>> decode_single('uint256', '0000000000000000000000000000000000000000000000000000000000003039')
This example should be removed.

2018-01-23 16:54 UTC, pipermerriam commented on README.md
> +    >>> decode_single('uint256', '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0009')
This example should be changed to be a bytestring `b'\x00\x00....'`

2018-01-23 16:54 UTC, pipermerriam commented on README.md
> +hexidecimal representation with or without the ``0x`` prefix.
Same here.  Remove indication that hexadecimal data is supported as it has been deprecated.

2018-01-23 17:43 UTC, palash25 commented
@pipermerriam please review

2018-01-23 18:34 UTC, pipermerriam approved these changes
Looks good. Lets see if CI passes and I'll get this merged.  Once we have the gitcoin claim issue resolved I'll get payment issued.

2018-01-23 18:34 UTC, pipermerriam commented on README.md
> +    >>> decode_single('uint256', '0x0000000000000000000000000000000000000000000000000000000000003039')
This example should be removed.

2018-01-23 18:34 UTC, pipermerriam commented on README.md
> +    >>> decode_abi(['uint256'], '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0009')
These strings need to be prefixed with `b` to make them bytestrings.

2018-01-23 18:34 UTC, pipermerriam commented on README.md
> +    '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0009'
This should be a bytestring. (same with the next one)

2018-01-24 10:48 UTC, palash25 commented
@pipermerriam the CI has passed. I think this can be merged.

2018-01-24 19:24 UTC, merged